<div align="center">

# 🐼 S14 — pandas aplicado al portafolio
### Lenguajes de Programación · Ingeniería Financiera

*De columnas sueltas a una tabla que se puede interrogar*

</div>

---

En S13 aprendiste NumPy: arrays, operaciones vectorizadas, funciones de estadística. Hoy conoces **pandas** — la librería que organiza datos de distinto tipo (texto, enteros, decimales) en una sola tabla con nombres.

| Bloque | Tema |
|:---:|---|
| 00 | ¿Qué es pandas y para qué se usa? |
| 01 | La estructura: Series y DataFrame |
| 02 | Cómo se importa pandas |
| 03 | Sintaxis básica: creación y exploración |
| 04 | Selección de datos |
| 05 | Operaciones más usadas |
| 06 | Todo junto: el portafolio como DataFrame |
| 07 | 🎯 Reto individual |

## 00 · ¿Qué es pandas y para qué se usa?

> **Nota** — Objetivo: entender qué problema resuelve pandas, y por qué no basta con lo que ya sabes de NumPy.

Un portafolio real no es solo números: tiene tickers (texto), cantidades (enteros), precios (decimales) y, más adelante, fechas. NumPy asume que todo el array es del mismo tipo — por eso necesitas algo que junte columnas de distinto tipo en una sola tabla, con nombres. Eso es exactamente lo que resuelve **pandas**.

pandas es una librería para trabajar con datos organizados en tablas: leerlos, explorarlos, limpiarlos, filtrarlos y resumirlos. Está construida sobre NumPy — por dentro, cada columna de una tabla de pandas es un array.

> 💡 **Idea clave** — NumPy responde *"¿cómo calculo rápido sobre muchos números?"*. pandas responde *"¿cómo organizo datos de distinto tipo en algo que se pueda leer, filtrar y consultar como una tabla?"*. No compiten — pandas usa NumPy por dentro.

📚 Fuente: ["Package overview", pandas.pydata.org](https://pandas.pydata.org/docs/getting_started/overview.html)

---
## 01 · La estructura: Series y DataFrame

> **Nota** — Objetivo: distinguir las dos estructuras de datos que ofrece pandas.

pandas ofrece dos tipos de estructuras:

- **Series** — un arreglo unidimensional etiquetado, capaz de contener datos de cualquier tipo. Es una sola columna, con índice.
- **DataFrame** — una estructura de dos dimensiones que guarda datos como una tabla, con filas y columnas. Cada columna de un DataFrame es, de hecho, una Series.

In [ ]:
import numpy as np
import pandas as pd

precios = pd.Series([195, 385, 185, 165])
print(precios)
print(type(precios))

0    195
1    385
2    185
3    165
dtype: int64
<class 'pandas.Series'>

In [ ]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio": [195, 385, 185, 165]
})
print(portafolio)
print(type(portafolio))

  ticker  cantidad  precio
0   AAPL        10     195
1   MSFT         8     385
2   AMZN        12     185
3  GOOGL         6     165
<class 'pandas.DataFrame'>

📚 Fuente: ["10 minutes to pandas" — "Basic data structures in pandas", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#basic-data-structures-in-pandas)

---
## 02 · Cómo se importa pandas

> **Nota** — Objetivo: importar pandas correctamente, junto con NumPy.

In [ ]:
import numpy as np
import pandas as pd

print("pandas", pd.__version__, "listo para usar.")

pandas 3.0.2 listo para usar.

`as pd` es la convención que usa toda la comunidad — casi nunca vas a ver `import pandas` solo, sin el apodo. pandas casi siempre se importa junto con NumPy, porque lo usa por dentro.

---
## 03 · Sintaxis básica: creación y exploración

> **Nota** — Objetivo: crear un DataFrame desde cero y explorarlo antes de calcular nada.

Un DataFrame se crea a partir de un diccionario, donde cada clave se convierte en el nombre de una columna:

In [ ]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio_compra": [180, 400, 170, 150],
    "precio_actual": [195, 385, 185, 165]
})

portafolio

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
1   MSFT         8            400            385
2   AMZN        12            170            185
3  GOOGL         6            150            165

**✏️ Completa el código** — explora el DataFrame antes de calcular nada, igual que hiciste con los precios de Yahoo Finance en S13.

In [ ]:
print(portafolio.head())     # primeras filas
print(portafolio.shape)     # (filas, columnas)
print(portafolio.dtypes)    # tipo de cada columna
print(portafolio.describe())     # resumen estadístico

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
1   MSFT         8            400            385
2   AMZN        12            170            185
3  GOOGL         6            150            165
(4, 4)
ticker             str
cantidad         int64
precio_compra    int64
precio_actual    int64
dtype: object
        cantidad  precio_compra  precio_actual
count   4.000000       4.000000       4.000000
mean    9.000000     225.000000     232.500000
std     2.581989     117.331439     102.428837
min     6.000000     150.000000     165.000000
25%     7.500000     165.000000     180.000000
50%     9.000000     175.000000     190.000000
75%    10.500000     235.000000     242.500000
max    12.000000     400.000000     385.000000

<details>
<summary>💡 Ver respuesta</summary>

```python
print(portafolio.head())
print(portafolio.shape)
print(portafolio.dtypes)
print(portafolio.describe())
```
</details>

> 💡 **Idea clave** — `.describe()` no es un método nuevo que memorizar desde cero: junta varias de las funciones que ya conoces de NumPy (`mean`, `std`, `min`, `max`) y te las entrega de una vez, columna por columna.

📚 Fuente: ["10 minutes to pandas" — "Viewing data", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#viewing-data)

---
## 04 · Selección de datos

> **Nota** — Objetivo: extraer columnas, filas y subconjuntos de un DataFrame.

| Sintaxis | Qué selecciona |
|---|---|
| `portafolio["ticker"]` | una sola columna (Series) |
| `portafolio[["ticker", "cantidad"]]` | varias columnas (DataFrame) |
| `portafolio.loc[0]` | una fila, por su etiqueta |
| `portafolio.iloc[0]` | una fila, por su posición |

In [ ]:
print(portafolio["ticker"])
print(portafolio.loc[0])

0     AAPL
1     MSFT
2     AMZN
3    GOOGL
Name: ticker, dtype: str
ticker           AAPL
cantidad           10
precio_compra     180
precio_actual     195
Name: 0, dtype: object

**✏️ Completa el código** — filtra el portafolio para quedarte solo con los activos donde `cantidad` sea mayor a 8.

In [ ]:
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
muchas_unidades

  ticker  cantidad  precio_compra  precio_actual
0   AAPL        10            180            195
2   AMZN        12            170            185

<details>
<summary>💡 Ver respuesta</summary>

```python
muchas_unidades = portafolio[portafolio["cantidad"] > 8]
```
</details>

> 💡 **Idea clave** — En S13 viste que comparar un array con un número (`ganancia > 0`) devuelve un array de verdadero/falso. Eso es exactamente lo que pasa por dentro cuando filtras un DataFrame: `portafolio["cantidad"] > 8` genera esa misma máscara, y pandas la usa para quedarse solo con las filas donde es verdadera.

📚 Fuente: ["10 minutes to pandas" — "Selection", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#selection)

---
## 05 · Operaciones más usadas

> **Nota** — Objetivo: agregar columnas calculadas y resumir un DataFrame sin ciclos.

Agregar una columna nueva es tan simple como asignarla — pandas alinea los valores automáticamente.

**✏️ Completa el código**

In [ ]:
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())   # promedio
print(portafolio["ganancia"].std())   # desviación estándar
portafolio.sort_values(by="ganancia")

75.0
135.27749258468683

  ticker  cantidad  precio_compra  precio_actual  valor_actual  ganancia
1   MSFT         8            400            385          3080      -120
3  GOOGL         6            150            165           990        90
0   AAPL        10            180            195          1950       150
2   AMZN        12            170            185          2220       180

<details>
<summary>💡 Ver respuesta</summary>

```python
portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])

print(portafolio["ganancia"].mean())
print(portafolio["ganancia"].std())
portafolio.sort_values(by="ganancia")
```
</details>

| Operación | Qué hace |
|---|---|
| `df["col"] = ...` | crea o reemplaza una columna |
| `df["col"].mean() / .std()` | estadísticas sobre una columna |
| `df.sort_values(by="col")` | ordena las filas según una columna |
| `df[condición]` | filtra filas |

📚 Fuente: ["10 minutes to pandas" — "Operations", pandas.pydata.org](https://pandas.pydata.org/docs/user_guide/10min.html#operations)

---
## 06 · Todo junto: el portafolio como DataFrame

> **Nota** — Objetivo: integrar creación, columnas calculadas, filtro y orden en un solo flujo.

In [ ]:
portafolio = pd.DataFrame({
    "ticker": ["AAPL", "MSFT", "AMZN", "GOOGL"],
    "cantidad": [10, 8, 12, 6],
    "precio_compra": [180, 400, 170, 150],
    "precio_actual": [195, 385, 185, 165]
})

portafolio["valor_actual"] = portafolio["cantidad"] * portafolio["precio_actual"]
portafolio["ganancia"] = portafolio["valor_actual"] - (portafolio["cantidad"] * portafolio["precio_compra"])
portafolio["rendimiento"] = (portafolio["ganancia"] / (portafolio["cantidad"] * portafolio["precio_compra"])) * 100

en_perdida = portafolio[portafolio["rendimiento"] < 0]
portafolio.sort_values(by="rendimiento", ascending=False)

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
3,GOOGL,6,150,165,990,90,10.000000
2,AMZN,12,170,185,2220,180,8.823529
0,AAPL,10,180,195,1950,150,8.333333
1,MSFT,8,400,385,3080,-120,-3.750000

**🔎 Pregunta de análisis**

Compara este bloque de código con el que escribiste en S11-S12 usando `for` y diccionarios. ¿Qué parte del código viejo desapareció por completo? ¿Qué se volvió más corto y por qué?

**✍️ Mi respuesta**

**¿Qué desapareció por completo?** El ciclo `for` que recorría el diccionario activo por activo, junto con las variables que se iban llenando dentro del ciclo (acumuladores, listas auxiliares) y el acceso manual a cada valor por su clave. En pandas no hay que decirle a Python *cómo* recorrer los datos: se le dice *qué* calcular.

**¿Qué se volvió más corto y por qué?** Los tres cálculos (`valor_actual`, `ganancia`, `rendimiento`) pasaron de ser operaciones repetidas dentro de un ciclo a una sola línea por columna, porque pandas aplica la operación a toda la columna a la vez (vectorizado, sobre NumPy). El filtro de los activos en pérdida pasó de un `if` dentro del ciclo con un `append` a una sola condición (`portafolio["rendimiento"] < 0`), y el orden pasó de ordenar listas o diccionarios a mano a `sort_values`. El resultado es menos código, más fácil de leer y con menos lugares donde equivocarse.

---
## 🎯 07 · Reto individual

Retoma el portafolio que te asignaron en el reto de S11-S12.

In [ ]:
# Datos asignados a mí (los de "Copiar mis datos para el cuaderno"; son los mismos de S11-S12 y S13).
# Misma estructura que la plantilla: cantidad y precio_compra por activo, y precios de hoy aparte.
mi_portafolio_dict = {
    "NFLX": {"cantidad": 16, "precio_compra": 284},
    "V":    {"cantidad": 14, "precio_compra": 295},
    "TSLA": {"cantidad": 15, "precio_compra": 423},
    "JPM":  {"cantidad": 8,  "precio_compra": 288},
}
mis_precios_dict = {"NFLX": 298, "V": 306, "TSLA": 352, "JPM": 232}

print("Mi portafolio asignado:")
print(mi_portafolio_dict)
print("Precios actuales:", mis_precios_dict)

Mi portafolio asignado:
{'NFLX': {'cantidad': 16, 'precio_compra': 284}, 'V': {'cantidad': 14, 'precio_compra': 295}, 'TSLA': {'cantidad': 15, 'precio_compra': 423}, 'JPM': {'cantidad': 8, 'precio_compra': 288}}
Precios actuales: {'NFLX': 298, 'V': 306, 'TSLA': 352, 'JPM': 232}

### Tu tarea

Con `mi_portafolio_dict` y `mis_precios_dict`:

1. Construye un DataFrame con las columnas `ticker`, `cantidad`, `precio_compra`, `precio_actual`.
2. Agrega las columnas `valor_actual`, `ganancia` y `rendimiento`.
3. Filtra los activos en pérdida.
4. Ordena el DataFrame de mayor a menor rendimiento.

In [ ]:
import pandas as pd
from IPython.display import display

# --- 1) DataFrame: ticker, cantidad, precio_compra, precio_actual ---
mi_df = (
    pd.DataFrame.from_dict(mi_portafolio_dict, orient="index")   # una fila por activo
      .rename_axis("ticker")
      .reset_index()                                              # ticker pasa a ser columna
)
mi_df["precio_actual"] = mi_df["ticker"].map(mis_precios_dict)    # alinea el precio de hoy por ticker

print("1) DataFrame base")
display(mi_df)

# --- 2) Columnas calculadas ---
mi_df["valor_actual"] = mi_df["cantidad"] * mi_df["precio_actual"]
mi_df["ganancia"] = mi_df["valor_actual"] - (mi_df["cantidad"] * mi_df["precio_compra"])
mi_df["rendimiento"] = (mi_df["ganancia"] / (mi_df["cantidad"] * mi_df["precio_compra"])) * 100

print("\n2) Con valor_actual, ganancia y rendimiento (%)")
display(mi_df.round(2))

# --- 3) Activos en pérdida ---
en_perdida = mi_df[mi_df["rendimiento"] < 0]

print("\n3) Activos en pérdida")
display(en_perdida.round(2))

# --- 4) Orden de mayor a menor rendimiento ---
ordenado = mi_df.sort_values(by="rendimiento", ascending=False)

print("\n4) Ordenado de mayor a menor rendimiento")
display(ordenado.round(2))

# --- Datos para el exit ticket ---
primero = ordenado.iloc[0]["ticker"]
ultimo = ordenado.iloc[-1]["ticker"]
n_perdida = len(en_perdida)
print(f"\nPrimero: {primero} | Último: {ultimo} | Activos en pérdida: {n_perdida}")

1) DataFrame base

  ticker  cantidad  precio_compra  precio_actual
0   NFLX        16            284            298
1      V        14            295            306
2   TSLA        15            423            352
3    JPM         8            288            232

2) Con valor_actual, ganancia y rendimiento (%)

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
0,NFLX,16,284,298,4768,224,4.93
1,V,14,295,306,4284,154,3.73
2,TSLA,15,423,352,5280,-1065,-16.78
3,JPM,8,288,232,1856,-448,-19.44

3) Activos en pérdida

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
2,TSLA,15,423,352,5280,-1065,-16.78
3,JPM,8,288,232,1856,-448,-19.44

4) Ordenado de mayor a menor rendimiento

,ticker,cantidad,precio_compra,precio_actual,valor_actual,ganancia,rendimiento
0,NFLX,16,284,298,4768,224,4.93
1,V,14,295,306,4284,154,3.73
2,TSLA,15,423,352,5280,-1065,-16.78
3,JPM,8,288,232,1856,-448,-19.44

Primero: NFLX | Último: JPM | Activos en pérdida: 2

### Exit ticket

«Mi portafolio, ordenado de mayor a menor rendimiento, tiene a **NFLX** primero y a **JPM** último. **2** activos están en pérdida.»